### PR TITLE
Fix decision interrupted state; allow skipping interrupted state in QC

### LINKED ISSUE #691: BUG: Decision interrupted path drops into combat

### PR DESCRIPTION
**Pull request by smartin015**
Fixes #691, #690

### CODE REVIEW

File: services/app/src/components/views/quest/cardtemplates/decision/Actions.tsx [hunk 1]
```diff
@@ -206,9 +207,10 @@ function pushDecisionRoll(node: ParserNode, roll: number, getState: () => AppSta
   decision.rolls.push(roll);
 
   // Based on the outcome, navigate to a roleplay card
-  const settings = getState().settings;
-  const rp = getState().multiplayer;
-  const outcome = computeOutcome(decision.rolls, selected, settings, node, rp);
+  const {settings, multiplayer, card} = getState();
+  console.log(node.getVisibleKeys());
```
Comment (toddmedema) [inline services/app/src/components/views/quest/cardtemplates/decision/Actions.tsx]: rm console log?

**Comment by toddmedema** [comment]
Also, could we get a matching update to the docs on this functionality?
