### PR TITLE
fix: update the api readme and config setupdb

### LINKED ISSUE #536: Steps for setup local env under API service are depreciated

### PR DESCRIPTION
**Pull request by nimish-gupta**
Fixes #536

### CODE REVIEW

File: services/api/src/config.ts [hunk 1]
```diff
@@ -10,6 +10,7 @@ nconf.argv()
   // Quest storage config settings
   'DATABASE_URL', // URL of postgres database storing quest metadata, user data, feedback, etc.
   'SEQUELIZE_LOGGING', // Enable console logging of sequelize SQL queries
+  'SEQUELIZE_SSL',
```
Comment (nimish-gupta) [inline services/api/src/config.ts]: For local setup, secure SSL setup is not required.

File: services/api/src/config.ts [hunk 2]
```diff
@@ -64,6 +65,7 @@ nconf.argv()
   PORT: 8081,
   SEQUELIZE_LOGGING: true,
   SUPER_USER_IDS: [],
+  SEQUELIZE_SSL: true,
```
Comment (nimish-gupta) [inline services/api/src/config.ts]: Setup default to true, so that we don't have to do any changes in the production

File: services/api/src/models/Database.ts [hunk 3]
```diff
@@ -77,13 +77,15 @@ export class Database {
       ],
       timestamps: false, // TODO: eventually switch to sequelize timestamps
     });
+    this.analyticsEvent.sync();
```
Comment (nimish-gupta) [inline services/api/src/models/Database.ts]: Added these because on starting the app, tables were not being created.

File: services/api/src/lib/oauth2.ts [hunk 4]
```diff
@@ -77,10 +78,11 @@ export function installOAuthRoutes(db: Database, router: express.Router) {
   // then they will be redirected to that URL when the flow is finished.
   // This also fetches their info from the DB and returns that (if available).
   // [START authorize]
-  router.post('/auth/google', // LOGIN
+  router.post('/auth/google', limitCors, // LOGIN
```
Comment (nimish-gupta) [inline services/api/src/lib/oauth2.ts]: As it was throwing error `No access-control-allow-origin` error on local
