### PR TITLE
Bug 7 players

### LINKED ISSUE #811: Bug: Can select 7 ppl with multitouch
And then no quests show up in search

Obv don't want to cap it behind the scenes without telling them, since that'd be confusing ... perhaps we show a modal on the next screen saying "you tried 7+ people, but we capped it to 6 since Expedition only supports 1-6 players"

### PR DESCRIPTION
**Pull request by Lordtien**
In the case of more than 6 players, a dialog saying "Too many players" open up.
Peek 2020-01-29 17-05

Issue: Once the dialog is canceled, the splash screen sticks to the last state and requires an additional touch to reset. I need help there.

Fixes #811

### CODE REVIEW

**Comment by Lordtien** [comment]
@toddmedema As the PR description mentions, I need to reset the splash screen post dialog cancellation. I cannot find a way to do that. Can you provide some info?

**Comment by toddmedema** [comment]
You'd probably want to reset state to its initial value: https://github.com/ExpeditionRPG/expedition/blob/master/services/app/src/components/views/SplashScreen.tsx#L27

**Comment by Lordtien** [comment]
Update: Made the change. Here's a GIF (Player limit set to 0 for testing):
Peek 2020-01-29 17-05

File: services/app/src/Init.tsx [hunk 1]
```diff
@@ -95,8 +95,10 @@ function setupDevice() {
     // https://stackoverflow.com/a/43502958/1332186
     if (/Android/.test(navigator.appVersion)) {
       window.addEventListener('resize', () => {
-        if (document.activeElement.tagName === 'INPUT' || document.activeElement.tagName === 'TEXTAREA') {
-          document.activeElement.scrollIntoView();
+        if (document.activeElement !== null) {
```
Comment (toddmedema) [inline services/app/src/Init.tsx]: In JS, you can also abbreviate this by just checking if (document.activeElement), since if it's null, it'll be falsey :)

File: services/app/src/components/base/Dialogs.test.tsx [hunk 2]
```diff
@@ -245,4 +245,27 @@ describe('Dialogs', () => {
       expect(e.find('#play').length).toEqual(0);
     });
   });
+
+  describe('TooManyPlayersDialog', () => {
```
Comment (toddmedema) [inline services/app/src/components/base/Dialogs.test.tsx]: Thank you for adding a test!

File: services/app/src/components/base/Dialogs.tsx [hunk 3]
```diff
@@ -208,6 +208,35 @@ export class ExpansionSelectDialog extends React.Component<ExpansionSelectDialog
...
 }
 
+export class TooManyPlayersDialog<T extends BaseDialogProps> extends React.Component<T, {}> {
+  protected title: string;
+  protected content: JSX.Element;
+
+  constructor(props: T) {
+    super(props);
+    this.title = 'Too many players!';
+    this.content = <p>Expedition can only be played by a maximum of 6 players!</p>;
```
Comment (toddmedema) [inline services/app/src/components/base/Dialogs.tsx]: I'd replace the exclamation mark in contents with a period, since there's already one in the title and too many exclamation marks comes off a bit strong

File: services/app/src/Init.tsx (hunk 1 above)
Comment (Lordtien) [reply services/app/src/Init.tsx]: Got it.

File: services/app/src/components/base/Dialogs.tsx (hunk 3 above)
Comment (Lordtien) [reply services/app/src/components/base/Dialogs.tsx]: Alrighty. Thanks.
