### PR TITLE
Fix quest ratings and new quest email, add tests

### LINKED ISSUE #692: BUG: Publishing resets ratings even when not a major release
Specifically, check out the quest `Z.E.#2 Tensions Rising`

We should fix this, and also restore the ratings on this quest.

Probably related to the fact that we keep getting "new quest published" emails for quests that already exist...

### LINKED ISSUE #705: Feature: confirmation dialog on major release

### PR DESCRIPTION
**Pull request by smartin015**
Fixes #692
Closes #705

### CODE REVIEW

File: services/quests/src/components/DialogsContainer.tsx [hunk 1]
```diff
@@ -28,6 +28,7 @@ const mapDispatchToProps = (dispatch: Redux.Dispatch<any>): DialogsDispatchProps
       dispatch(setDialog(dialog, false));
     },
     onRequestPublish: (quest: QuestType, majorRelease: boolean, privatePublish: boolean): void => {
+      console.log('major release:', majorRelease);
```
Comment (toddmedema) [inline services/quests/src/components/DialogsContainer.tsx]: console log
